### PR TITLE
Move <haskell/> and <hask/> aliases for syntax highlighting into a new extension - remove related logic from LocalSettings.php

### PR DESCRIPTION
**Pull request by taezaz**
Related Issue: https://github.com/haskell/haskell-wiki-configuration/issues/30

### CODE REVIEW

**Comment by taezaz** [comment]
@hgolden 

Potential issues:
1. There are no unit tests. This being said - I've checked the "SyntaxHighlight_GeSHi" tests and they don't seem to be doing much either and thought it might be a bit excessive to write a test for this, but if you think it's worth adding them anyway, let me know.
2. I've tried to add "SyntaxHighlight_GeSHi" as a dependency in extension.json, but couldn't manage to get Mediawiki to detect that it's installed. I checked the documentation and it seems that the module needs to register somehow and only then it can be detected. "SyntaxHighlight_GeSHi" doesn't seem to be doing that.

**Review by hgolden — CHANGES_REQUESTED** [review]
@taezaz

Please make this a full-fledged extension (register it for independent use) and write unit tests. I believe this is a better practice than simply including the extension in only the Haskell wiki. Comments?

**Comment by taezaz** [comment]
@hgolden
I'd be happy to add the unit tests, but I don't think registering this extension for public use is worth the effort. It's a normal practice to write extensions just for your own use as that's a useful way to encapsulate behavior specific to your website.

In addition to that, public extensions have a large number of prerequisites that need to be satisfied. They need to be maintained and their users supported. Also, Mediawiki states that it can take up to [two years](https://www.mediawiki.org/wiki/Manual:Developing_extensions#Deploying_and_registering) for an extension to get approved and listed which probably doesn't happen often but still it might potentially require a long-term investment into extension development. 

All this makes me conclude that you should only bother publishing extensions if you're passionate about Mediawiki extension development or are in such business which I am not and I don't think this is important for Haskell Wiki future, but correct me if I am wrong.

I don't want to make it seem that I am avoiding the work - I really feel that it's unnecessary. I am very keen on helping the Haskell community and infrastructure, but I do have a limited time for that and I'd rather focus on what I am good at and what I can manage sustainably.

Do you think it will be enough to add unit tests? Do you have any other comments regarding the code?

**Comment by hgolden** [comment]
@taezaz 

Thank you for your thoughtful reply and all the work you have already done!

> @hgolden I'd be happy to add the unit tests, but I don't think registering this extension for public use is worth the effort. It's a normal practice to write extensions just for your own use as that's a useful way to encapsulate behavior specific to your website.

I wasn't aware of the work involved. It would be of little benefit, so I agree with your position.

> Do you have any other comments regarding the code?

Your code looks fine to me. Thanks again. Once you have added the tests I will merge.

**Comment by taezaz** [comment]
@hgolden 
I've added the tests. Please have a look. Thanks! :)

**Comment by hgolden** [comment]
I will look in a few days. This morning I had sinus surgery and I'll be out of it for a couple days. Thanks for your prompt work!

**Comment by taezaz** [comment]
@hgolden Sounds good. Get well soon! :)

**Comment by hgolden** [comment]
@taezaz, sorry for the delay! It's taken me longer to recover from the surgery than I expected, but I'm better now. I will review your PR tomorrow.

**Comment by hgolden** [comment]
@taezaz, great! Thanks!

**Pull request merged**
